# Generated by Django 3.0.9 on 2020-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
