# Generated by Django 3.0.9 on 2020-08-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpFileData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importers.FileStorage')),
            ],
        ),
    ]
