# Generated by Django 3.0.9 on 2020-08-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0002_dumpfiledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumpfiledata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='dumpfiledata',
            name='town',
        ),
    ]
